### ISSUE TITLE
What is nctmpco.cfg?

### ISSUE THREAD

**Issue by bartnijssen** [mrstu/IS-cfg-edit#3]
Is this a temporary file that is generated on the fly? In that case it should not be part of the repo. The contents are nearly identical to `globalatts-vic.cfg`. Unless I hear otherwise, I am not planning to edit this file.

**Comment by mrstu** [comment]
No need to edit that.  It's just the template that I use to define
sections/keywords.

These are really all I think you need to look at:

globalatts-{ulm,vic}.cfg
vars-{ulm,vic}.cfg

**Comment by bartnijssen** [comment]
OK - sounds good - I issued you a pull request that you should review before merging
